[package]
name = "cli_conf_spring_boot"
version = "0.1.0"
edition = "2024"

[dependencies]
owo-colors = "4.2.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_yaml = "0.9.34"
thiserror = "2.0.18"
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
